[general]
import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[window]
opacity = 1
padding.x = 4
padding.y = 4
decorations = "Full"

[font]
normal.family = "IosBerkMono Medium"
bold.family = "IosBerkMono SemiBold"
size = 12.0

# [terminal.shell]
# program = "/usr/bin/tmux"
# args = ["new-session", "-A", "-D"]

